# Numpy Cheat Sheet

In [2]:
import numpy as np

## Creating arrays

In [3]:
# 1D
a = np.array([1,2,3])

# 2D
b = np.array([(1,2,3),(4,5,6)], dtype=float)

# 3D
c = np.array([(1,2,3),(4,5,6),(7,8,9)], dtype=float)

print(a)
print(b)
print(c)

[1 2 3]
[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## Initial Placeholders

In [6]:
print(np.zeros((3,4))) # an array of zeros
print(np.ones((2,3,4),dtype=np.int16)) # an array of ones
print(np.arange(10,25,5)) # array of evenly spaced values - step
print(np.linspace(0,2,9)) # evenly spaced values - no of samples
print(np.full((2,2),7)) # constant array
print(np.eye(2))
print(np.random.random((2,2))) # random valued array
print(np.empty((3,4))) # empty array


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[10 15 20]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.94684732 0.46511842]
 [0.54008011 0.84371753]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Saving and Loading

In [7]:
# Saving as a npy file
np.save('data/my_array',a)
np.savez('data/array.npz',a,b)
print(np.load('data/my_array.npy'))

[1 2 3]


In [19]:
# loding from as a text file
print(np.loadtxt('data/myfile.txt'))

[1. 2. 3. 4. 5.]


In [20]:
# generating from text file
print(np.genfromtxt('data/myfile.csv',delimiter=','))

[[1. 2. 3. 4. 5.]
 [6. 7. 8. 9. 0.]
 [5. 6. 7. 8. 9.]]


In [23]:
# saving a numpy variable to a file
np.savetxt("data/myarray.csv",b,delimiter=",")

## Inspecting Arrays

In [4]:
print(a.shape, b.shape)
print(len(a), len(b))
print(b.ndim)
print(c.size)
print(b.dtype)
print(b.dtype.name)
print(b.astype(int)) # type conversion


(3,) (2, 3)
3 2
2
9
float64
float64
[[1 2 3]
 [4 5 6]]


In [11]:
print(np.int64)
print(np.float32)
print(np.bool)
print(np.bytes_)
print(np.str_)

<class 'numpy.int64'>
<class 'numpy.float32'>
<class 'numpy.bool'>
<class 'numpy.bytes_'>
<class 'numpy.str_'>


## Array Maths

In [14]:
g = a - b
print(g)
print(np.subtract(a,b))

[[ 0.  0.  0.]
 [-3. -3. -3.]]
[[ 0.  0.  0.]
 [-3. -3. -3.]]


In [16]:
h = a + b
print(h)
print(np.add(a,b))

[[2. 4. 6.]
 [5. 7. 9.]]
[[2. 4. 6.]
 [5. 7. 9.]]


In [17]:
i = a / b
print(i)
print(np.divide(a,b))

[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]]
[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]]


In [18]:
j = a * b
print(j)
print(np.multiply(a,b))

[[ 1.  4.  9.]
 [ 4. 10. 18.]]
[[ 1.  4.  9.]
 [ 4. 10. 18.]]


In [21]:
print(np.exp(b))
print(np.sqrt(b))
print(np.sin(a))
print(np.cos(b))
print(np.log(a))
print(g.dot(np.transpose(g)))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[0.84147098 0.90929743 0.14112001]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[0.         0.69314718 1.09861229]
[[ 0.  0.]
 [ 0. 27.]]


## Comparison

In [23]:
print(a==b)
print(a<2)
print(np.array_equal(a,b))

[[ True  True  True]
 [False False False]]
[ True False False]
False


## Aggregate functions

In [24]:
print(a.sum())
print(a.min())
print(b.max(axis=0))
print(b.cumsum(axis=1))
print(a.mean())
print(np.median(b))
print(np.corrcoef(a))
print(np.std(b))

6
1
[4. 5. 6.]
[[ 1.  3.  6.]
 [ 4.  9. 15.]]
2.0
3.5
1.0
1.707825127659933


## Copying Arrays

In [25]:
h = a.view()
h[0] = 3
print(a)
print(h)

[3 2 3]
[3 2 3]


In [26]:
i = np.copy(a)
i[0] = 5
print(a)
print(i)

[3 2 3]
[5 2 3]


In [27]:
h = a.copy()
h[0]=10
print(a)
print(h)

[3 2 3]
[10  2  3]


## Sorting

In [33]:
a=np.array([4,2,33,6,4])
a.sort()
print(a)
c = np.array([(4,2,4,6),(3,4,6,1)])
c.sort(axis=0)
print(c)
c = np.array([(4,2,4,6),(3,4,6,1)])
c.sort(axis=1)
print(c)

[ 2  4  4  6 33]
[[3 2 4 1]
 [4 4 6 6]]
[[2 4 4 6]
 [1 3 4 6]]


## Subsetting

In [34]:
print(a)
print(a[2])
print(b)
print(b[1,2])

[ 2  4  4  6 33]
4
[[1. 2. 3.]
 [4. 5. 6.]]
6.0


## Boolean Indexing

In [37]:
print(a)
print(a[a<6])

[ 2  4  4  6 33]
[2 4 4]


## Fancy Indexing

In [38]:
print(b)
print(b[[1,0,1,0],[0,1,2,0]])

print(b[[1,0,1,0]][:,[0,1,2,0]])

[[1. 2. 3.]
 [4. 5. 6.]]
[4. 2. 6. 1.]
[[4. 5. 6. 4.]
 [1. 2. 3. 1.]
 [4. 5. 6. 4.]
 [1. 2. 3. 1.]]


## Slicing

In [35]:
print(a)
print(a[0:2])
print(a[::-1])

print(b)
print(b[0:2,1])

print(c)
print(c[1,...])

[ 2  4  4  6 33]
[2 4]
[33  6  4  4  2]
[[1. 2. 3.]
 [4. 5. 6.]]
[2. 5.]
[[2 4 4 6]
 [1 3 4 6]]
[1 3 4 6]


## Array Manipulation

In [40]:
## Transpose

print(b)
i = np.transpose(b)
print(i)
print(i.T)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 4.]
 [2. 5.]
 [3. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [44]:
## Changing Array Shape

print(b.ravel())
print(b)
print(b.reshape(3,-2))

[1. 2. 3. 4. 5. 6.]
[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [50]:
## Resize

h = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
h.resize((2,6))
print(h)

h=np.array([1,2,3])
h.resize((2,6))
print(h)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[1 2 3 0 0 0]
 [0 0 0 0 0 0]]


In [55]:
## Adding and deleting elements

h = np.array([1,2,3])
g = np.array([4,5,6])
print(np.append(h,g))

print(np.insert(a,1,5))

print(np.delete(a,[1]))

[1 2 3 4 5 6]
[ 2  5  4  4  6 33]
[ 2  4  6 33]


## Combining Arrays

In [65]:
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])

print(np.concatenate((a,b), axis=0))
print(np.vstack((a,b,b)))
print(np.hstack((a,b,b)))
print(np.column_stack((a,b,b)))
print(np.r_[a,b,b])
print(np.c_[a,b,b])

[1 2 3 4 5 3 4 5 6 7]
[[1 2 3 4 5]
 [3 4 5 6 7]
 [3 4 5 6 7]]
[1 2 3 4 5 3 4 5 6 7 3 4 5 6 7]
[[1 3 3]
 [2 4 4]
 [3 5 5]
 [4 6 6]
 [5 7 7]]
[1 2 3 4 5 3 4 5 6 7 3 4 5 6 7]
[[1 3 3]
 [2 4 4]
 [3 5 5]
 [4 6 6]
 [5 7 7]]


## Splitting arrays

In [79]:
a = np.array([1,2,3,4,5,6])
b = np.vstack((a,a,a,a))
print(np.hsplit(a,3))
print(np.vsplit(b,2))

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]]), array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])]
